/* ============================================================
   LEVEL · Mapas Interativos — dados do mapa GRIDLOCK (Black Ops 7)
   Callouts oficiais (Expressway, Street, Underpass, Onsen, Restaurant,
   Promenade, Delivery Truck/A, Ramp Up/B, Fine Dining/Γ).
   Textos reescritos nas minhas palavras (PT-BR + EN) — nada copiado.
   Coordenadas no espaço VERTICAL 1100×1760 (retrato).
   Bilingue: interface {pt,en} + termos técnicos via TERMS[...].
   ============================================================ */
(function () {
  // -------- termos técnicos (PT-BR / EN do jogo) --------
  const TERMS = {
    hardpoint: { pt: 'Hardpoint',          en: 'Hardpoint' },
    flag:      { pt: 'Bandeira',           en: 'Flag' },
    bombsite:  { pt: 'Local de Bomba',     en: 'Bomb Site' },
    spawn:     { pt: 'Spawn',              en: 'Spawn' },
    sightline: { pt: 'Linha de Tiro',      en: 'Sightline' },
    powerpos:  { pt: 'Posição de Poder',   en: 'Power Position' },
    highground:{ pt: 'Terreno Alto',       en: 'High Ground' },
    route:     { pt: 'Rotação',            en: 'Rotation' },
    hotspot:   { pt: 'Zona de Combate',    en: 'Hotspot' },
    hardcover: { pt: 'Cobertura',          en: 'Hard Cover' },
    lethal:    { pt: 'Letal',              en: 'Lethal' },
    door:      { pt: 'Entrada · rua',      en: 'Entrance · street' },
    window:    { pt: 'Janela · 1º andar',  en: 'Window · 1st floor' },
    tip:       { pt: 'Dica avançada',      en: 'Advanced tip' },
  };
  const CLASS = {
    AR:  { pt: 'Fuzil de Assalto', en: 'Assault Rifle', short: 'AR',  key: 'AR'  },
    SMG: { pt: 'Submetralhadora',  en: 'SMG',           short: 'SMG', key: 'SMG' },
    SNP: { pt: 'Sniper',           en: 'Sniper',        short: 'SNP', key: 'SNP' },
    LMG: { pt: 'Metralhadora',     en: 'LMG',           short: 'LMG', key: 'LMG' },
    MAR: { pt: 'Fuzil de Precisão',en: 'Marksman',      short: 'MAR', key: 'MAR' },
  };

  // -------- meta do mapa --------
  const MAP = {
    id: 'gridlock',
    name: 'Gridlock',
    mode: { pt: 'Hardpoint · Dominação', en: 'Hardpoint · Domination' },
    size: { pt: 'Médio · Híbrido', en: 'Medium · Hybrid' },
    bestClass: 'AR',
    bestBuild: 'DOLORE ETERNO',
    summary: {
      pt: 'Via expressa japonesa que desabou sobre o distrito comercial. Tiroteios de média distância pelas avenidas, CQB caótico nos escombros e flancos verticais pelo Restaurante e pelo Onsen. Um fuzil versátil cobre quase tudo — troque para SMG nos flancos.',
      en: 'Collapsed Japanese expressway over the downtown shopping district. Mid-range fights down the avenues, chaotic CQB in the rubble and vertical flanks through the Restaurant and Onsen. A versatile AR covers most of it — swap to an SMG on the flanks.',
    },
    // -------- Prebrief (reescrito nas minhas palavras) --------
    prebrief: {
      pt: 'Gridlock é um mapa de tamanho médio (que estreou no Black Ops 4) ambientado numa via expressa japonesa que desabou depois de um assalto, derrubando o trânsito sobre o distrito comercial lá embaixo. O combate acontece sobre as ruínas da Via Expressa, agora no mesmo nível da cidade: de um lado o Onsen (casa de banhos) com o muro externo destruído, do outro uma fileira de veículos e lojas pela Rua, e a Passagem Inferior cortando por baixo. É um mapa que mistura tiroteios longos pelas avenidas com brigas apertadas nos interiores — leia os três níveis: rua (rotações rápidas e arriscadas), interiores (avanços seguros mas lentos) e o 1º andar/plataformas (poleiros de sniper que trancam a Via Expressa).',
      en: 'Gridlock is a mid-sized map (first introduced in Black Ops 4) set on a Japanese expressway that collapsed after a heist, dropping the traffic onto the shopping district below. Fighting plays out over the ruins of the Expressway, now level with the city: an Onsen bathhouse with a blown-out outer wall on one side, a row of vehicles and shops down the Street on the other, and the Underpass cutting beneath. It blends long avenue gunfights with tight interior brawls — read it on three levels: street (fast, risky rotations), interiors (safe but slow pushes) and the upper floors/platforms (sniper perches that lock the Expressway).',
    },
    // -------- Itens Interessantes para Usar (= Gridlock Intel, nas minhas palavras) --------
    items: [
      { icon: 'scope', name: { pt: 'Mira híbrida', en: 'Hybrid sight' },
        why: { pt: 'Gridlock mistura tiros de longa distância na rua com brigas curtas nos interiores. Uma mira híbrida resolve os dois mundos: zoom baixo no curto e magnificação extra para varrer rotas longas como a Passagem Inferior e a Rua.', en: 'Gridlock mixes long street shots with close interior brawls. A hybrid sight covers both worlds: low zoom up close, extra magnification to sweep long routes like the Underpass and the Street.' } },
      { icon: 'drone', name: { pt: 'Perk Tracker (Rastreador)', en: 'Tracker Perk' },
        why: { pt: 'Mostra a direção do próximo inimigo mais próximo a cada abate — poderoso num mapa grande. Combine perks vermelho + azul para ativar a especialidade Scout e encadear abates sem aparecer no minimapa inimigo, mesmo sem supressor.', en: 'Shows the direction of the next closest enemy after each kill — powerful on a larger map. Pair red + blue perks for the Scout specialty to chain kills while staying off the enemy minimap, even without a suppressor.' } },
      { icon: 'rocket', name: { pt: 'Lança-foguetes', en: 'Launcher' },
        why: { pt: 'As scorestreaks aéreas castigam bastante em Gridlock, mesmo com tanta cobertura por cima. Se o time inimigo encher o céu de UAVs e helicópteros, troque para um lança-foguetes e derrube-os.', en: 'Aerial scorestreaks hit hard on Gridlock despite all the overhead cover. If the enemy fills the sky with UAVs and helos, switch to a launcher and bring them down.' } },
    ],
  };

  // -------- camadas (ordem do painel) --------
  const LAYERS = [
    { id: 'objetivos', icon: 'flag',  color: '#FF9800', label: { pt: 'Objetivos',        en: 'Objectives' },     desc: { pt: 'Hardpoints, bandeiras e bombas', en: 'Hardpoints, flags & bombs' } },
    { id: 'spawns',    icon: 'spawn', color: '#58C4DC', label: { pt: 'Spawns',           en: 'Spawns' },         desc: { pt: 'Nascimento dos times',           en: 'Team spawn zones' } },
    { id: 'sightlines',icon: 'cross', color: '#C77DFF', label: { pt: 'Linhas de tiro',   en: 'Sightlines' },     desc: { pt: 'Corredores de sniper',           en: 'Sniper lanes' } },
    { id: 'power',     icon: 'peak',  color: '#4ADE80', label: { pt: 'Posições de poder', en: 'Power positions' },desc: { pt: 'Domínio de zona / terreno alto',  en: 'Map control / high ground' } },
    { id: 'rotas',     icon: 'route', color: '#7CC4FF', label: { pt: 'Rotas de rotação', en: 'Rotations' },      desc: { pt: 'Caminhos de avanço',             en: 'Push paths' } },
    { id: 'hotspots',  icon: 'flame', color: '#F2784B', label: { pt: 'Pontos quentes',   en: 'Hotspots' },       desc: { pt: 'Onde mais se morre',             en: 'Highest-death zones' } },
    { id: 'cover',     icon: 'shield',color: '#8FA6C4', label: { pt: 'Cobertura',        en: 'Hard cover' },     desc: { pt: 'Veículos e muros sólidos',       en: 'Vehicles & solid walls' } },
    { id: 'lethals',   icon: 'bomb',  color: '#FFC857', label: { pt: 'Letais',           en: 'Lethals' },        desc: { pt: 'Bons spots de granada',          en: 'Best grenade spots' } },
    { id: 'entradas',  icon: 'door',  color: '#34D399', color2: '#C77DFF', label: { pt: 'Entradas',         en: 'Entrances' },      desc: { pt: 'Rua (verde) · 1º andar/sniper (violeta)', en: 'Street (green) · upper/sniper (violet)' } },
    { id: 'dicas',     icon: 'bulb',  color: '#F472B6', label: { pt: 'Dicas avançadas',  en: 'Advanced tips' },  desc: { pt: 'Pontos oficiais do guia do mapa', en: 'Official spots from the map guide' } },
  ];

  function F(o) { return o; }

  // -------- features (coordenadas em 1920×1080) --------
  const FEATURES = [
    // ===== OBJETIVOS =====
    F({ id: 'obj-plaza', layer: 'objetivos', geom: 'point', x: 560, y: 880, term: 'hardpoint',
        name: { pt: 'Via Expressa (centro)', en: 'Expressway (center)' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'O Hardpoint mais disputado e o coração do mapa, onde a via desabou. Não segure por dentro — controle as entradas a partir das colunas ao sul. Quem domina os dois acessos domina o ponto.',
               en: 'The most contested Hardpoint and the heart of the map, where the freeway came down. Don\u2019t hold it from inside — lock the entrances from the south pillars. Control the two entries and you control the point.' },
        playstyle: { pt: 'Jogue média distância, recuo controlado.', en: 'Play mid-range with controlled recoil.' } }),
    F({ id: 'obj-rest', layer: 'objetivos', geom: 'point', x: 380, y: 1240, term: 'flag',
        name: { pt: 'Restaurante', en: 'Restaurant' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Talvez o ponto mais forte do mapa. O interior tem três cantos com ângulos poderosos para a Rua, a Via Expressa e de volta para o Calçadão — segure-os e castiga meia avenida de longe sem se expor. Mas o flanco é a fraqueza: vigie as escadas e a entrada de fora, é por aí que pegam você por trás. Quem domina o Restaurante sufoca a circulação inimiga no mapa inteiro.',
               en: 'Maybe the strongest spot on the map. Inside, three corners give powerful angles onto the Street, the Expressway and back toward the Promenade — hold them and you punish half the avenue from range without exposing yourself. But your flank is the weakness: watch the stairs and the outside entrance, that\u2019s where they get behind you. Owning the Restaurant chokes enemy movement across the whole map.' },
        playstyle: { pt: 'Agressivo, slide e tiro de quadril.', en: 'Aggressive, slide and hip-fire.' } }),
    F({ id: 'obj-onsen', layer: 'objetivos', geom: 'point', x: 850, y: 1030, term: 'bombsite',
        name: { pt: 'Onsen', en: 'Onsen' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Pátio fechado com os banhos no centro servindo de cobertura, e o muro externo destruído abrindo um flanco. Plante a bomba no lado oeste do deck — você tem recuo imediato para o cruzamento se a defesa girar.',
               en: 'Enclosed courtyard with the baths breaking up cover, and the blown-out outer wall opening a flank. Plant on the west side of the deck — you get an instant fallback to the junction if the defense rotates.' },
        playstyle: { pt: 'CQB com colete para sobreviver a letais.', en: 'CQB with flak to survive lethals.' } }),
    F({ id: 'obj-viaduto', layer: 'objetivos', geom: 'point', x: 430, y: 580, term: 'flag',
        name: { pt: 'Via Expressa · Plataforma', en: 'Expressway · Platform' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Bandeira em terreno alto sobre o tabuleiro de concreto da via caída. Domina meia avenida e a entrada central — mas você fica exposto aos snipers da Passagem Inferior. Mexa-se entre os pilares.',
               en: 'High-ground flag on the concrete deck of the fallen freeway. Dominates half the avenue and the central entry — but you\u2019re exposed to Underpass snipers. Move between the pillars.' },
        playstyle: { pt: 'Marksman: primeiro tiro certeiro.', en: 'Marksman: first-shot accuracy.' } }),

    // ===== SPAWNS =====
    F({ id: 'spawn-a', layer: 'spawns', geom: 'zone', x: 500, y: 150, w: 210, h: 78, team: 'A', term: 'spawn',
        name: { pt: 'Spawn · Lado da Rua', en: 'Street-Side Spawn' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Nascimento norte, do lado da Rua. As primeiras rotações descem pela Via Expressa — corra para a plataforma e ganhe o primeiro duelo de terreno alto antes do inimigo chegar.',
               en: 'North spawn, on the Street side. Opening rotations go down the Expressway — sprint to the platform to win the first high-ground duel before the enemy arrives.' },
        playstyle: { pt: 'Abra com fuzil, ocupe o alto cedo.', en: 'Open with AR, seize the high ground early.' } }),
    F({ id: 'spawn-b', layer: 'spawns', geom: 'zone', x: 460, y: 1520, w: 200, h: 76, team: 'B', term: 'spawn',
        name: { pt: 'Spawn · Passagem Inferior', en: 'Underpass Spawn' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Nascimento sul, perto do Restaurante e da rampa. Pressione aqui para forçar a virada de spawn — mas cuidado: é onde o inimigo reaparece atrás de você se empurrar demais.',
               en: 'South spawn, near the Restaurant and the ramp. Pressure here to force a spawn flip — but beware, it\u2019s where the enemy reappears behind you if you over-push.' },
        playstyle: { pt: 'Contenha, não invada sozinho.', en: 'Contain it, don\u2019t solo-dive.' } }),

    // ===== SIGHTLINES =====
    F({ id: 'sl-west', layer: 'sightlines', geom: 'line', from: [330, 580], to: [345, 1180], term: 'sightline',
        name: { pt: 'Rua', en: 'Street' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'Corredor reto de spawn a spawn pela fileira de lojas e veículos — uma das melhores lanes de sniper do mapa. Fique junto ao ônibus e vigie o cruzamento norte. Fumaça anula a linha por completo.',
               en: 'Straight spawn-to-spawn corridor past the shops and vehicles — one of the best sniper lanes on the map. Set up by the bus and watch the north junction. Smoke shuts it down completely.' },
        playstyle: { pt: 'Sniper de hold, saia após 2 abates.', en: 'Hold-sniper, relocate after 2 kills.' } }),
    F({ id: 'sl-east', layer: 'sightlines', geom: 'line', from: [470, 360], to: [800, 720], term: 'sightline',
        name: { pt: 'Passagem Inferior', en: 'Underpass' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'Rota longa que passa por baixo da via — atenção ao túnel escuro no meio, onde SMGs esperam. Boa para cobrir quem planta no Onsen.',
               en: 'Long route that dips under the freeway — watch the dark tunnel mid-lane where SMGs wait. Good for covering the Onsen plant.' },
        playstyle: { pt: 'Sniper com secundária ágil pronta.', en: 'Sniper with a fast secondary ready.' } }),
    F({ id: 'sl-viaduto', layer: 'sightlines', geom: 'line', from: [420, 560], to: [660, 700], term: 'sightline',
        name: { pt: 'Linha da Plataforma', en: 'Platform Line' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'O tabuleiro da via é uma plataforma elevada e reta. Quem o segura vê a Via Expressa inteira — mas o vão desabado corta a linha, então ninguém te flanqueia por ali.',
               en: 'The freeway deck is a raised, straight platform. Holding it sees the whole Expressway — but the collapsed gap cuts the line, so no one flanks you across it.' },
        playstyle: { pt: 'Marksman firme, recuo curto.', en: 'Marksman, planted, short recoil.' } }),

    // ===== POWER POSITIONS =====
    F({ id: 'pw-viaduto', layer: 'power', geom: 'point', x: 400, y: 540, term: 'highground',
        name: { pt: 'Plataforma da Via Expressa', en: 'Expressway Platform' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'O melhor terreno alto do mapa: ângulo de cima para a Via Expressa e para a Rua. Combine com a bandeira da plataforma — segure os dois e domina metade do mapa.',
               en: 'The best high ground on the map: top-down angle onto the Expressway and the Street. Pair it with the platform flag — hold both and you own half the map.' },
        playstyle: { pt: 'Fuzil a média, fique recuado da borda.', en: 'Mid-range AR, sit back off the edge.' } }),
    F({ id: 'pw-varanda', layer: 'power', geom: 'point', x: 330, y: 1120, term: 'powerpos',
        name: { pt: 'Varanda do Restaurante', en: 'Restaurant Balcony' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Sobranceira ao Calçadão e à bandeira do Restaurante. Defenda a flag daqui em vez de por dentro — você pega quem entra de surpresa pela rua.',
               en: 'Overlooks the Promenade and the Restaurant flag. Defend the flag from here instead of inside — you catch anyone pushing in off the street.' },
        playstyle: { pt: 'Fuzil controlado, ângulos de cima.', en: 'Controlled AR, top angles.' } }),
    F({ id: 'pw-roofeast', layer: 'power', geom: 'point', x: 880, y: 940, term: 'powerpos',
        name: { pt: 'Telhado · Passagem', en: 'Underpass Rooftop' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Posição alta que cobre o lado leste da Via Expressa e a aproximação ao Onsen. Pouco usada — ótima para um marksman paciente flanquear a rotação inimiga.',
               en: 'Elevated spot covering the east side of the Expressway and the Onsen approach. Under-used — perfect for a patient marksman to flank the enemy rotation.' },
        playstyle: { pt: 'Marksman de flanco, tiros de oportunidade.', en: 'Flank marksman, picks of opportunity.' } }),

    // ===== ROTAS (por time — aparecem ao clicar no spawn) =====
    F({ id: 'rt-center', layer: 'rotas', geom: 'route', team: 'A', path: [[560, 250], [560, 520], [560, 800]], term: 'route',
        name: { pt: 'Avanço pela Via Expressa', en: 'Expressway Push' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Rota do time A (Rua). Caminho mais curto do spawn norte ao centro. Rápido mas exposto às duas avenidas — só use com fumaça ou se o seu time já segura a plataforma.',
               en: 'Team A (Street) route. Shortest path from north spawn to the center. Fast but exposed to both avenues — only take it with smoke or once your team holds the platform.' },
        playstyle: { pt: 'Fuzil pronto, não corra a descoberto.', en: 'AR up, don\u2019t sprint in the open.' } }),
    F({ id: 'rt-west', layer: 'rotas', geom: 'route', team: 'A', path: [[470, 270], [300, 540], [300, 1060], [380, 1200]], term: 'route',
        name: { pt: 'Flanco pela Rua', en: 'Street Flank' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Rota do time A. Desça a Rua usando a cobertura dos veículos e entre no Restaurante por trás. A rota de SMG por excelência — chega ao flanco inimigo antes da troca central.',
               en: 'Team A route. Drop down the Street using vehicle cover and enter the Restaurant from behind. The SMG route of choice — reach the enemy flank before the central trade.' },
        playstyle: { pt: 'SMG, movimento constante.', en: 'SMG, constant movement.' } }),
    F({ id: 'rt-east', layer: 'rotas', geom: 'route', team: 'A', path: [[700, 270], [820, 540], [840, 880], [858, 1010]], term: 'route',
        name: { pt: 'Flanco pela Passagem', en: 'Underpass Flank' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Rota do time A. Pela Passagem Inferior e o túnel até o Onsen. Passa pelo ponto cego do sniper da Rua — ideal para abrir o local da bomba sem ser visto de frente.',
               en: 'Team A route. Down the Underpass and tunnel to the Onsen. Passes through the Street sniper\u2019s blind spot — ideal to crack the bomb site unseen from the front.' },
        playstyle: { pt: 'SMG com supressor, flanco profundo.', en: 'Suppressed SMG, deep flank.' } }),
    F({ id: 'rtb-center', layer: 'rotas', geom: 'route', team: 'B', path: [[555, 1470], [558, 1200], [560, 1000], [560, 900]], term: 'route',
        name: { pt: 'Avanço pela Via Expressa (B)', en: 'Expressway Push (B)' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Rota do time B (Passagem). Sobe direto pelo centro até a Via Expressa. Rápida mas exposta — leve fumaça para cobrir as janelas que olham para o corredor central.',
               en: 'Team B (Underpass) route. Pushes straight up the middle to the Expressway. Fast but exposed — bring smoke to cover the windows watching the center lane.' },
        playstyle: { pt: 'Fuzil pronto, fume antes de subir.', en: 'AR up, smoke before you climb.' } }),
    F({ id: 'rtb-street', layer: 'rotas', geom: 'route', team: 'B', path: [[480, 1470], [360, 1200], [320, 860], [330, 650]], term: 'route',
        name: { pt: 'Flanco pela Rua (B)', en: 'Street Flank (B)' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Rota do time B. Sobe a Rua pela esquerda usando os veículos como cobertura para flanquear quem segura o centro a partir da plataforma. Boa para virar o spawn inimigo.',
               en: 'Team B route. Climbs the Street on the left using the vehicles as cover to flank whoever holds the center from the platform. Good for flipping the enemy spawn.' },
        playstyle: { pt: 'SMG, suba colado à cobertura.', en: 'SMG, hug the cover going up.' } }),
    F({ id: 'rtb-onsen', layer: 'rotas', geom: 'route', team: 'B', path: [[660, 1470], [770, 1240], [835, 1110], [850, 1035]], term: 'route',
        name: { pt: 'Flanco pelo Onsen (B)', en: 'Onsen Flank (B)' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Rota do time B. Entra no Onsen pela direita para tomar o local da bomba ou cair atrás de quem defende o centro pelo lado leste.',
               en: 'Team B route. Enters the Onsen from the right to take the bomb site or drop behind whoever defends the center from the east side.' },
        playstyle: { pt: 'SMG, entre rápido e limpe os cantos.', en: 'SMG, enter fast and clear the corners.' } }),

    // ===== HOTSPOTS =====
    F({ id: 'hs-escombros', layer: 'hotspots', geom: 'point', x: 540, y: 730, term: 'hotspot',
        name: { pt: 'Escombros da Via Expressa', en: 'Expressway Rubble' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'O vão desabado da via: combate caótico e de altíssima proximidade sobre os destroços. Evite atravessar a pé — atire de uma cobertura ou contorne pelo centro.',
               en: 'The collapsed freeway gap: chaotic point-blank combat over the debris. Avoid crossing on foot — shoot from cover or go around through the center.' },
        playstyle: { pt: 'SMG ou shotgun, reflexos.', en: 'SMG or shotgun, reflexes.' } }),
    F({ id: 'hs-crossS', layer: 'hotspots', geom: 'point', x: 520, y: 1080, term: 'hotspot',
        name: { pt: 'Cruzamento Sul', en: 'South Junction' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Cruzamento de quatro vias onde as rotações do centro e do Restaurante colidem. Pré-aponte as quinas — quem atira primeiro quase sempre ganha.',
               en: 'Four-way junction where center and Restaurant rotations collide. Pre-aim the corners — whoever shoots first almost always wins.' },
        playstyle: { pt: 'Fuzil pré-apontado nas quinas.', en: 'AR pre-aimed on corners.' } }),
    F({ id: 'hs-crossN', layer: 'hotspots', geom: 'point', x: 660, y: 520, term: 'hotspot',
        name: { pt: 'Cruzamento Norte', en: 'North Junction' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Choque das primeiras rotações de spawn. Toma muito tiro de sniper das duas avenidas — passe rápido e use o caminhão como escudo.',
               en: 'Clash of the opening spawn rotations. Takes heavy sniper fire from both avenues — cross fast and use the truck as a shield.' },
        playstyle: { pt: 'Fuzil, atravesse com cobertura.', en: 'AR, cross behind cover.' } }),

    // ===== COVER =====
    F({ id: 'cv-bus', layer: 'cover', geom: 'point', x: 330, y: 1010, term: 'hardcover',
        name: { pt: 'Ônibus da Rua', en: 'Street Bus' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'Cobertura sólida no meio da Rua. Encoste para um posto de sniper seguro ou para recarregar no meio de uma troca longa.',
               en: 'Solid cover mid-way down the Street. Tuck in for a safe sniper post or to reload mid-way through a long trade.' },
        playstyle: { pt: 'Qualquer arma; use como âncora.', en: 'Any weapon; use as an anchor.' } }),
    F({ id: 'cv-truck', layer: 'cover', geom: 'point', x: 700, y: 500, term: 'hardcover',
        name: { pt: 'Caminhões de Bombeiros', en: 'Fire Trucks' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Os caminhões de bombeiros vermelhos sob a Passagem dão cobertura sólida e ainda deixam subir para um ângulo elevado. Use-os para segurar a Passagem ou para um wall jump rápido sobre quem avança por baixo.',
               en: 'The red fire trucks under the Underpass give solid cover and let you climb for an elevated angle. Use them to hold the Underpass or for a quick wall jump over players pushing below.' },
        playstyle: { pt: 'Marksman; suba para o ângulo, desça para cobrir.', en: 'Marksman; climb for the angle, drop for cover.' } }),
    F({ id: 'cv-cars', layer: 'cover', geom: 'point', x: 600, y: 990, term: 'hardcover',
        name: { pt: 'Carros Encravados', en: 'Jammed Cars' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Fileira de carros que dá a única cobertura segura para atravessar ao centro. Pule de carro em carro em vez de correr reto.',
               en: 'Row of cars giving the only safe cover to cross into the center. Hop car to car instead of running straight.' },
        playstyle: { pt: 'SMG, saltos curtos entre coberturas.', en: 'SMG, short hops between cover.' } }),

    // ===== LETHALS =====
    F({ id: 'le-plaza', layer: 'lethals', geom: 'point', x: 480, y: 740, term: 'lethal',
        name: { pt: 'Granada na Via Expressa', en: 'Frag onto Expressway' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Da plataforma, jogue em arco para o centro da via. Limpa o Hardpoint sem você se expor — sincronize com o avanço do seu time.',
               en: 'From the platform, arc a frag into the center lane. Clears the Hardpoint without exposing yourself — time it with your team\u2019s push.' },
        playstyle: { pt: 'Jogue antes do seu time entrar.', en: 'Throw just before your team enters.' } }),
    F({ id: 'le-rest', layer: 'lethals', geom: 'point', x: 380, y: 1300, term: 'lethal',
        name: { pt: 'Molotov no Corredor', en: 'Molotov Corridor' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Incendiária no corredor estreito de entrada do Restaurante. Nega a rotação inimiga ou força eles a sair para a sua mira.',
               en: 'Incendiary in the Restaurant\u2019s narrow entry corridor. Denies the enemy rotation or forces them out into your line.' },
        playstyle: { pt: 'Bloqueie, depois empurre com SMG.', en: 'Block, then push with the SMG.' } }),
    F({ id: 'le-onsen', layer: 'lethals', geom: 'point', x: 820, y: 1090, term: 'lethal',
        name: { pt: 'C4 no Onsen', en: 'C4 at Onsen' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Cole C4 no banho central e detone quando a defesa se agrupar para impedir a planta. Devastador em rodadas de Procurar e Destruir.',
               en: 'Stick C4 on the central bath and detonate when the defense stacks to stop the plant. Devastating in Search & Destroy rounds.' },
        playstyle: { pt: 'Detone no agrupamento defensivo.', en: 'Pop it on the defensive stack.' } }),

    // ===== ENTRADAS (rua = verde · 1º andar/sniper = violeta) =====
    F({ id: 'en-rest', layer: 'entradas', geom: 'entrance', level: 'street', x: 400, y: 1190, term: 'door',
        name: { pt: 'Porta do Restaurante', en: 'Restaurant Door' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Entrada principal da bandeira, virada para o Calçadão. Limpe o interior com SMG — quem entra de fuzil fica lento nas curvas.',
               en: 'Main flag entrance facing the Promenade. Clear the interior with an SMG — pushing in with an AR is too slow around the corners.' },
        playstyle: { pt: 'Slide para dentro, tiro de quadril.', en: 'Slide in, hip-fire.' } }),
    F({ id: 'en-a1', layer: 'entradas', geom: 'entrance', level: 'street', x: 330, y: 680, term: 'door',
        name: { pt: 'Loja A1 · Rua', en: 'Shop A1 · Street' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Saída direta para a Rua e a lane de sniper. Espie antes — esta porta está na mira do ônibus.',
               en: 'Opens straight onto the Street and the sniper lane. Peek first — this door sits in the bus\u2019s line of fire.' },
        playstyle: { pt: 'Fuzil, espie curto e recue.', en: 'AR, short peek and pull back.' } }),
    F({ id: 'en-b1', layer: 'entradas', geom: 'entrance', level: 'street', x: 600, y: 430, term: 'door',
        name: { pt: 'Acesso · Cruzamento Norte', en: 'Access · North Junction' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Entrada que liga o cruzamento norte ao centro. Bom acesso para girar ao Hardpoint por dentro, longe dos snipers.',
               en: 'Entry linking the north junction to the center. A good way to rotate onto the Hardpoint from inside, away from snipers.' },
        playstyle: { pt: 'Fuzil de média, rotação interior.', en: 'Mid AR, interior rotation.' } }),
    F({ id: 'en-c2', layer: 'entradas', geom: 'entrance', level: 'street', x: 560, y: 1080, term: 'door',
        name: { pt: 'Acesso · Cruzamento Sul', en: 'Access · South Junction' }, weaponClass: 'AR', build: 'DOLORE ETERNO',
        tip: { pt: 'Porta sobre o cruzamento sul — entrada de flanco para o centro pelo lado leste. Sincronize com o avanço central.',
               en: 'Door onto the south junction — a flank entry to the center from the east. Time it with the central push.' },
        playstyle: { pt: 'Fuzil, entre após a primeira troca.', en: 'AR, enter after the first trade.' } }),
    F({ id: 'en-d2', layer: 'entradas', geom: 'entrance', level: 'street', x: 800, y: 1080, term: 'door',
        name: { pt: 'Acesso · Passagem', en: 'Underpass Access' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Acesso discreto à Passagem Inferior e ao túnel. Rota de SMG para chegar ao Onsen pelo ponto cego do sniper.',
               en: 'Quiet access to the Underpass and tunnel. An SMG route to reach the Onsen through the sniper\u2019s blind spot.' },
        playstyle: { pt: 'SMG com supressor, flanco profundo.', en: 'Suppressed SMG, deep flank.' } }),
    F({ id: 'en-a2', layer: 'entradas', geom: 'entrance', level: 'street', x: 330, y: 900, term: 'door',
        name: { pt: 'Meia · Rua', en: 'Street Mid' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'Entrada no meio da Rua, junto ao ônibus. Use para cair em cima de quem segura a lane de sniper.',
               en: 'Mid-Street entrance by the bus. Use it to drop onto whoever is holding the sniper lane.' },
        playstyle: { pt: 'SMG, flanqueie o sniper.', en: 'SMG, flank the sniper.' } }),

    // -- 1º andar / janela (spots de sniper) --
    F({ id: 'up-b1', layer: 'entradas', geom: 'entrance', level: 'upper', x: 440, y: 1040, term: 'window',
        name: { pt: 'Janela do Restaurante · sobre a Via', en: 'Restaurant Window · over Expressway' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'A famosa janela destruída do Restaurante, com ângulo direto para o centro da Via Expressa. O melhor poleiro de sniper para trancar o ponto — mas é o primeiro lugar que o inimigo confere.',
               en: 'The famous crumbled Restaurant window, angled straight onto the center of the Expressway. The best sniper perch to lock the point — but it\u2019s the first place the enemy checks.' },
        playstyle: { pt: 'Sniper, troque de janela após 2 abates.', en: 'Sniper, switch windows after 2 kills.' } }),
    F({ id: 'up-c1', layer: 'entradas', geom: 'entrance', level: 'upper', x: 480, y: 640, term: 'window',
        name: { pt: 'Janela da Plataforma · sobre a Via', en: 'Platform Window · over Expressway' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'No lado oposto à janela do Restaurante. Cobre a entrada do centro e a boca do túnel — par perfeito para uma dupla de snipers cruzar fogo.',
               en: 'On the side opposite the Restaurant window. Covers the center entry and the tunnel mouth — perfect for a sniper duo to crossfire.' },
        playstyle: { pt: 'Sniper, cruze com a janela do Restaurante.', en: 'Sniper, crossfire with the Restaurant window.' } }),
    F({ id: 'up-a2', layer: 'entradas', geom: 'entrance', level: 'upper', x: 330, y: 600, term: 'window',
        name: { pt: 'Janela · Rua', en: 'Window · Street' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'Poleiro alto que enfia a Rua inteira de spawn a spawn. Domina uma das melhores lanes do mapa — fumaça é a única resposta.',
               en: 'High perch that threads the entire Street spawn-to-spawn. Owns one of the best lanes on the map — smoke is the only answer.' },
        playstyle: { pt: 'Sniper de hold, recue se fumarem.', en: 'Hold-sniper, fall back if smoked.' } }),
    F({ id: 'up-d2', layer: 'entradas', geom: 'entrance', level: 'upper', x: 890, y: 985, term: 'window',
        name: { pt: 'Janela · Passagem', en: 'Window · Underpass' }, weaponClass: 'SNP', build: 'OLHAR FRIO',
        tip: { pt: 'Janela que cobre a Passagem Inferior e a planta no Onsen. Ideal para apoiar quem entra na bomba sem você se expor no chão.',
               en: 'Window covering the Underpass and the Onsen plant. Ideal to support the bomb push without exposing yourself on the ground.' },
        playstyle: { pt: 'Sniper de apoio, cubra a planta.', en: 'Support sniper, cover the plant.' } }),
    F({ id: 'up-c2', layer: 'entradas', geom: 'entrance', level: 'upper', x: 760, y: 900, term: 'window',
        name: { pt: 'Janela · Flanco Leste', en: 'Window · East Flank' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Janela baixa sobre o flanco leste da via. Menos óbvia — ótima para um marksman pegar quem gira ao Hardpoint.',
               en: 'Low window over the east flank of the lane. Less obvious — great for a marksman to pick off players rotating to the Hardpoint.' },
        playstyle: { pt: 'Marksman, tiros de oportunidade.', en: 'Marksman, picks of opportunity.' } }),

    // ===== DICAS AVANÇADAS (pontos oficiais do guia — reescritos nas minhas palavras) =====
    F({ id: 'adv-truck', layer: 'dicas', geom: 'point', x: 730, y: 560, term: 'tip',
        name: { pt: 'Caminhão de Entregas (A)', en: 'Delivery Truck (A)' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Entre no caminhão de entregas parado na curva entre a Rua e a Passagem Inferior. O ângulo não é tão alto quanto a janela do Restaurante do outro lado, mas você vê reto pela Rua e de volta para a Passagem. Precisa achar o inimigo rápido? Suba no teto para uma visão ampla — e exposta.',
               en: 'Climb into the delivery truck parked at the bend between the Street and the Underpass. The angle isn\u2019t as high as the Restaurant window opposite, but you see straight down the Street and back toward the Underpass. Need to find the enemy fast? Hop on the roof for a wide — and exposed — view.' },
        playstyle: { pt: 'Marksman; suba no teto só por instantes.', en: 'Marksman; only roof up for a moment.' } }),
    F({ id: 'adv-ramp', layer: 'dicas', geom: 'point', x: 410, y: 600, term: 'tip',
        name: { pt: 'Rampa (B)', en: 'Ramp Up (B)' }, weaponClass: 'MAR', build: 'OLHAR FRIO',
        tip: { pt: 'Do spawn da Passagem Inferior, as placas caídas da via formam uma rampa até uma plataforma sobre a Via Expressa. É a melhor visão do corredor central, só rivalizada pela janela destruída do Restaurante do lado oposto. Dá também para atirar rampa abaixo quando a Passagem esquenta — use como atalho para emboscar quem está embaixo.',
               en: 'From the Underpass spawn, the fallen freeway signs form a ramp to a platform over the Expressway. It\u2019s the best view of the center lane, matched only by the crumbled Restaurant window opposite. You can also fire down the ramp when the Underpass heats up — use it as a shortcut to ambush players below.' },
        playstyle: { pt: 'Marksman/fuzil, domine o centro.', en: 'Marksman/AR, command the center.' } }),
    F({ id: 'adv-dining', layer: 'dicas', geom: 'point', x: 380, y: 1260, term: 'tip',
        name: { pt: 'Alta Gastronomia (Γ)', en: 'Fine Dining (Γ)' }, weaponClass: 'SMG', build: 'VELO NOTURNO',
        tip: { pt: 'O Restaurante pode ser um dos pontos mais fortes do mapa. No interior há três cantos com ângulos poderosos para a Rua, a Via Expressa e de volta para o Calçadão. Fique de olho no flanco: inimigos sobem pelas escadas e entram pela parte de fora. Se segurar o lugar, o time adversário sofre para avançar enquanto você mira de longe.',
               en: 'The Restaurant can be one of the strongest spots on the map. Inside, three corners give powerful angles onto the Street, the Expressway and back toward the Promenade. Watch your flank: enemies come up the stairs and climb in from outside. Hold it and the enemy struggles to push up while you pick them off from range.' },
        playstyle: { pt: 'SMG dentro, fuzil para segurar os ângulos.', en: 'SMG inside, AR to hold the angles.' } }),
  ];

  // -------- rótulos de zona (nomes dos locais sobre o mapa) --------
  const ZONES = [
    { id: 'z-underpass',  x: 470,  y: 400,  name: { pt: 'Passagem Inferior', en: 'Underpass' } },
    { id: 'z-street',     x: 330,  y: 800,  name: { pt: 'Rua',               en: 'Street' } },
    { id: 'z-expressway', x: 560,  y: 950,  name: { pt: 'Via Expressa',       en: 'Expressway' } },
    { id: 'z-onsen',      x: 905,  y: 1155, name: { pt: 'Onsen',             en: 'Onsen' } },
    { id: 'z-promenade',  x: 440,  y: 1450, name: { pt: 'Calçadão',          en: 'Promenade' } },
  ];

  window.LevelMapData = { MAP, LAYERS, FEATURES, ZONES, TERMS, CLASS };
})();
